---
# yamllint disable rule:line-length
###############################################################################
# NFS Client Configuration
###############################################################################
# Configure NFS automounts via systemd or fstab.
#
# Args:
#   mount: dict - one element from nfs_mounts
#
# Reference:
# * https://wiki.archlinux.org/title/NFS#As_systemd_unit
# * https://wiki.debian.org/NFSServerSetup
# * https://github.com/zilexa/Homeserver/tree/master/filesystem/networkshares_HowTo-NFSv4.2

- name: 'Client | generate service name'
  ansible.builtin.set_fact:
    _nfs_systemd_name: '{{ mount.mount[1:] | replace("/", "-") }}'

- name: 'Client | systemd | enable automount'
  when: nfs_systemd_automount_enable
  ansible.builtin.include_role:
    name: 'r_pufky.srv.systemd'
  vars:
    mount_state: '{{ "present" if mount.state != "absent" }}'
    systemd_mounts:
      - name: '{{ _nfs_systemd_name }}'
        state: '{{ mount_state }}'
        drop_in: false
        unit:
          description: 'NFS mount {{ mount.server }}:{{ mount.export }}'
        mount:
          what: '{{ mount.server }}:{{ mount.export }}'
          where: '{{ mount.mount }}'
          type: 'nfs4'
          options: '{{ mount.options | default(nfs_role_default_mount_options) }}'
          directory_mode: '{{ mount.mode | default("0755") }}'
          timeout_sec: '{{ mount.timeout | default(30) }}'
        install:
          wanted_by:
            - 'multi-user.target'
    systemd_automounts:
      - name: '{{ _nfs_systemd_name }}'
        state: '{{ mount_state }}'
        drop_in: false
        unit:
          description: 'Automount NFS {{ mount.server }}:{{ mount.export }}'
        automount:
          where: '{{ mount.mount }}'
          directory_mode: '{{ mount.mode | default("0755") }}'
        install:
          wanted_by:
            - 'multi-user.target'

- name: 'Client | fstab'
  when: not nfs_systemd_automount_enable
  block:
    - name: 'Client | query mount point'
      ansible.builtin.stat:
        path: '{{ mount.mount }}'
      register: _nfs_query_mount

    # Mounted mount point will fail to set permissions even if root.
    - name: 'Client | create mount point'
      when: not _nfs_query_mount.stat.exists
      ansible.builtin.file:
        path: '{{ mount.mount }}'
        mode: '{{ mount.mode | default("0755") }}'
        state: 'directory'
      become: true

    - name: 'Client | create fstab mount'
      notify:
        - 'Handlers | reload systemd'
        - 'Handlers | mount -a'
      ansible.posix.mount:
        src: '{{ mount.server }}:{{ mount.export }}'
        path: '{{ mount.mount }}'
        opts: '{{ mount.options | default(nfs_role_default_mount_options) | join(",") }}'
        fstype: 'nfs4'
        state: '{{ mount.state }}'
