---
# yamllint disable rule:line-length
###############################################################################
# NFS Client Configuration
###############################################################################
# Configure NFS automounts via systemd or fstab.
#
# Args:
#   mount: dict - one element from nfs_cfg_mounts
#
# Reference:
# * https://wiki.archlinux.org/title/NFS#As_systemd_unit
# * https://wiki.debian.org/NFSServerSetup
# * https://github.com/zilexa/Homeserver/tree/master/filesystem/networkshares_HowTo-NFSv4.2
# yamllint enable rule:line-length

- name: 'Client | fact | generate service base name'
  ansible.builtin.set_fact:
    nfs__systemd_file: '{{
        nfs___app._systemd_d ~ "/" ~
        mount.mount[1:] | replace("/", "-")
      }}'

- name: '{{ "Client | filesystem | set " ~ nfs__systemd_file ~ ".mount" }}'
  when: nfs_flg_systemd_automount and mount.state != 'absent'
  notify: 'Handlers | systemd'
  ansible.builtin.template:
    src: 'systemd/client.mount.j2'
    dest: '{{ nfs__systemd_file ~ ".mount" }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Client | filesystem | set " ~ nfs__systemd_file ~ ".automount" }}'
  when: nfs_flg_systemd_automount and mount.state != 'absent'
  notify: 'Handlers | systemd'
  ansible.builtin.template:
    src: 'systemd/client.automount.j2'
    dest: '{{ nfs__systemd_file ~ ".automount" }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: '{{ "Client | filesystem | remove " ~ nfs__systemd_file ~ ".*" }}'
  when: nfs_flg_systemd_automount and mount.state == 'absent'
  notify: 'Handlers | systemd'
  ansible.builtin.file:
    path: '{{ nfs__systemd_file ~ item }}'
    state: 'absent'
  loop:
    - 'mount'
    - 'automount'

- name: 'Client | filesystem | fstab'
  when: not nfs_flg_systemd_automount
  block:
    - name: '{{ "Client | filesystem | query " ~ mount.mount }}'
      ansible.builtin.stat:
        path: '{{ mount.mount }}'
      register: nfs__query_mount

    # Mounted mount point will fail to set permissions even if root.
    - name: '{{ "Client | filesystem | create " ~ mount.mount }}'
      when: not nfs__query_mount.stat.exists
      ansible.builtin.file:
        path: '{{ mount.mount }}'
        mode: '{{ mount.mode | default("0755") }}'
        state: 'directory'
      become: true

    - name: 'Client | filesystem | create fstab mount'
      notify:
        - 'Handlers | systemd mount'
      ansible.posix.mount:
        src: '{{ mount.server }}:{{ mount.export }}'
        path: '{{ mount.mount }}'
        opts: '{{
            mount.options |
            default(nfs___app._default_mount_options) |
            join(",")
          }}'
        fstype: 'nfs4'
        state: '{{ mount.state }}'
