---
###############################################################################
# Disable NFS V2, V3
###############################################################################
# Hard disable NFSv2, NFSv3.
#
# Bookworm does not support V2; V3 should not be used in lieu of V4, which
# supports single socket, local file copies, state, authentication, encryption.
#
# PVE node require rpcbind services only for NFS; it is safe to disable if
# using V4.
#
# Disable systemd nfs-server using a drop-in in server.yml when the service is
# guaranteed to be installed.
#
# Decision: disable rpc-statd for client and server - testing showed that base
#     installs only used rpc-statd for NFS.
#
# Reference:
# * https://orca.pet/nfs4debian/
# * https://wiki.debian.org/NFSServerSetup
# * https://forum.proxmox.com/threads/nfsv4-server-disabled-under-pve-8.129803/

- name: 'Disable NFSv2, NFSv3 | disable legacy services'
  when: not nfs_legacy_services_enable
  ansible.builtin.systemd_service:
    name: '{{ item }}'
    masked: true
    state: 'stopped'
  loop:
    - 'rpcbind'
    - 'rpcbind.socket'
    - 'rpc-statd'
    - 'rpc-statd-notify'
