---
- name: 'Prep'
  ansible.builtin.import_tasks: 'prep.yml'

- name: 'Server'
  when: nfs_flg_server
  ansible.builtin.import_tasks: 'server.yml'

- name: 'Client'
  when: nfs_flg_client and nfs_cfg_mounts | length > 0
  ansible.builtin.include_tasks: 'client.yml'
  loop: '{{ nfs_cfg_mounts }}'
  loop_control:
    loop_var: 'mount'
    label: '{{ mount.mount }}'
