---
###############################################################################
# Prep
###############################################################################
# Parse _cfg_ defaults to generate runtime data and store in data annotations.
#
# Hard disable NFSv2, NFSv3.
#
# Bookworm does not support V2; V3 should not be used in lieu of V4, which
# supports single socket, local file copies, state, authentication, encryption.
#
# PVE node require rpcbind services only for NFS; it is safe to disable if
# using V4.
#
# Disable systemd nfs-server using a drop-in in server.yml when the service is
# guaranteed to be installed.
#
# Decision: disable rpc-statd for client and server - testing showed that base
#     installs only used rpc-statd for NFS.
#
# Reference:
# * https://orca.pet/nfs4debian/
# * https://wiki.debian.org/NFSServerSetup
# * https://forum.proxmox.com/threads/nfsv4-server-disabled-under-pve-8.129803/

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    nfs__cfg: "{{ {} | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _exports=nfs_cfg_exports,
        _mounts=nfs_cfg_mounts,
      ) }}"

- name: 'Prep | systemd | disable NFSv2, NFSv3 legacy services'
  when: not nfs_flg_legacy_services
  ansible.builtin.systemd:
    name: '{{ item }}'
    masked: true
    state: 'stopped'
  failed_when: false
  loop:
    - 'rpcbind'
    - 'rpcbind.socket'
    - 'rpc-statd'
    - 'rpc-statd-notify'

- name: 'Prep | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ nfs___server_packages if nfs_flg_server else [] }}'
      - '{{ nfs___client_packages if nfs_flg_client else [] }}'
    apt_srv_package_update_cache: true
