---
# yamllint disable rule:line-length
###############################################################################
# NFS Server Configuration
###############################################################################
# Bookworm+ only honors settings in /etc/nfs.conf.d/*:
#   nfs-utils (1:2.6.1-1) unstable; urgency=medium
#
#   On systems running systemd, changes to command-line options in
#   /etc/default/nfs-common or /etc/default/nfs-kernel-server will now
#   be ignored.  All those options can instead be set in /etc/nfs.conf
#   or /etc/nfs.conf.d/; see nfs.conf(5).
#
#   If either of the files in /etc/default has been changed, the
#   command-line options will be converted on upgrade to the file
#   /etc/nfs.conf.d/local.conf.
#
#   A future update to nfs-utils will remove the command-line options
#   in /etc/default entirely, so even on systems not using systemd
#   you should make changes in /etc/nfs.conf.d/ instead.
#
#   -- Ben Hutchings <benh@debian.org>  Sun, 13 Mar 2022 19:55:09 +0100
#
# PVE nodes only require rpcbind services only for NFS; it is safe to disable
# if using V4.
#
# Reference:
# * https://wiki.debian.org/NFSServerSetup
# * https://orca.pet/nfs4debian/
# * https://forum.proxmox.com/threads/nfsv4-server-disabled-under-pve-8.129803/

- name: 'Server | set /etc/nfs.conf.d/local.conf'
  notify:
    - 'Handlers | restart nfs-server'
    - 'Handlers | restart nfs-mountd'
  ansible.builtin.template:
    src: 'local.conf.j2'
    dest: '/etc/nfs.conf.d/local.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Server | set /etc/exports'
  notify:
    - 'Handlers | refresh exports'
  ansible.builtin.template:
    src: 'exports.j2'
    dest: '/etc/exports'
    owner: 'root'
    group: 'root'
    mode: '0644'
