---
# yamllint disable rule:line-length
###############################################################################
# NFS Handlers
###############################################################################

- name: 'Handlers | restart nfs-server'
  ansible.builtin.systemd:
    name: 'nfs-server'
    state: 'restarted'
    enabled: true
    daemon_reload: true

- name: 'Handlers | restart nfs-mountd'
  ansible.builtin.systemd:
    name: 'nfs-mountd'
    state: 'restarted'
    enabled: true
    daemon_reload: true

- name: 'Handlers | refresh exports'
  ansible.builtin.command: '/usr/sbin/exportfs -ra'
  changed_when: false

- name: 'Handlers | reload systemd'
  ansible.builtin.systemd:
    daemon_reload: true

- name: 'Handlers | mount -a'  # noqa command-instead-of-module mount all NFS shares at once
  ansible.builtin.command: '/usr/bin/mount -a'
  changed_when: true
